AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - db/**
    - config/**
    - script/**
    - !ruby/regexp /old_and_unused\.rb$/
    - app/helpers/**

LineLength:
  Max: 99
ClassLength:
  Max: 200